name: Compile LaTeX CV

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Compile LaTeX
              uses: xu-cheng/latex-action@v4
              with:
                  root_file: cv.tex
