name: Compile LaTeX CV

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Compile LaTeX
              uses: xu-cheng/latex-action@v4
              with:
                  root_file: cv.tex
                  latexmk_use_xelatex: true
            - name: Commit PDF
              run: |
                  git config --local user.email "action@github.com"
                  git config --local user.name "GitHub Action"
                  git add cv.pdf
                  git diff --staged --quiet || git commit -m "robot: Update compiled CV [skip ci]"
                  git push
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
