name: Compile LaTeX CV

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
              with:
                  token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
            - name: Build LaTeX document
              uses: dante-ev/latex-action@latest
              with:
                  root_file: cv.tex
                  compiler: xelatex
                  args: -interaction=nonstopmode -shell-escape
            - uses: actions/upload-artifact@v4
              with:
                  name: cv-pdf.zip
                  path: cv.pdf
            # - name: Commit PDF
            #   run: |
            #       git config --local user.email "action@github.com"
            #       git config --local user.name "GitHub Action"
            #       git add cv.pdf
            #       git diff --staged --quiet || git commit -m "robot: Update compiled CV [skip ci]"
            #       git push https://${{ secrets.PERSONAL_ACCESS_TOKEN }}@github.com/joshmtlau/curriculum_vitae.git
